package com.stratagile.pnrouter.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.stratagile.pnrouter.db.UserEntity;
import com.stratagile.pnrouter.db.RouterEntity;

import com.stratagile.pnrouter.db.UserEntityDao;
import com.stratagile.pnrouter.db.RouterEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userEntityDaoConfig;
    private final DaoConfig routerEntityDaoConfig;

    private final UserEntityDao userEntityDao;
    private final RouterEntityDao routerEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        routerEntityDaoConfig = daoConfigMap.get(RouterEntityDao.class).clone();
        routerEntityDaoConfig.initIdentityScope(type);

        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);
        routerEntityDao = new RouterEntityDao(routerEntityDaoConfig, this);

        registerDao(UserEntity.class, userEntityDao);
        registerDao(RouterEntity.class, routerEntityDao);
    }
    
    public void clear() {
        userEntityDaoConfig.clearIdentityScope();
        routerEntityDaoConfig.clearIdentityScope();
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

    public RouterEntityDao getRouterEntityDao() {
        return routerEntityDao;
    }

}
