package com.stratagile.pnrouter.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.stratagile.pnrouter.db.RouterUserEntity;
import com.stratagile.pnrouter.db.UserEntity;
import com.stratagile.pnrouter.db.RouterEntity;
import com.stratagile.pnrouter.db.RecentFile;
import com.stratagile.pnrouter.db.FriendEntity;

import com.stratagile.pnrouter.db.RouterUserEntityDao;
import com.stratagile.pnrouter.db.UserEntityDao;
import com.stratagile.pnrouter.db.RouterEntityDao;
import com.stratagile.pnrouter.db.RecentFileDao;
import com.stratagile.pnrouter.db.FriendEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig routerUserEntityDaoConfig;
    private final DaoConfig userEntityDaoConfig;
    private final DaoConfig routerEntityDaoConfig;
    private final DaoConfig recentFileDaoConfig;
    private final DaoConfig friendEntityDaoConfig;

    private final RouterUserEntityDao routerUserEntityDao;
    private final UserEntityDao userEntityDao;
    private final RouterEntityDao routerEntityDao;
    private final RecentFileDao recentFileDao;
    private final FriendEntityDao friendEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        routerUserEntityDaoConfig = daoConfigMap.get(RouterUserEntityDao.class).clone();
        routerUserEntityDaoConfig.initIdentityScope(type);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        routerEntityDaoConfig = daoConfigMap.get(RouterEntityDao.class).clone();
        routerEntityDaoConfig.initIdentityScope(type);

        recentFileDaoConfig = daoConfigMap.get(RecentFileDao.class).clone();
        recentFileDaoConfig.initIdentityScope(type);

        friendEntityDaoConfig = daoConfigMap.get(FriendEntityDao.class).clone();
        friendEntityDaoConfig.initIdentityScope(type);

        routerUserEntityDao = new RouterUserEntityDao(routerUserEntityDaoConfig, this);
        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);
        routerEntityDao = new RouterEntityDao(routerEntityDaoConfig, this);
        recentFileDao = new RecentFileDao(recentFileDaoConfig, this);
        friendEntityDao = new FriendEntityDao(friendEntityDaoConfig, this);

        registerDao(RouterUserEntity.class, routerUserEntityDao);
        registerDao(UserEntity.class, userEntityDao);
        registerDao(RouterEntity.class, routerEntityDao);
        registerDao(RecentFile.class, recentFileDao);
        registerDao(FriendEntity.class, friendEntityDao);
    }
    
    public void clear() {
        routerUserEntityDaoConfig.clearIdentityScope();
        userEntityDaoConfig.clearIdentityScope();
        routerEntityDaoConfig.clearIdentityScope();
        recentFileDaoConfig.clearIdentityScope();
        friendEntityDaoConfig.clearIdentityScope();
    }

    public RouterUserEntityDao getRouterUserEntityDao() {
        return routerUserEntityDao;
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

    public RouterEntityDao getRouterEntityDao() {
        return routerEntityDao;
    }

    public RecentFileDao getRecentFileDao() {
        return recentFileDao;
    }

    public FriendEntityDao getFriendEntityDao() {
        return friendEntityDao;
    }

}
