package com.stratagile.pnrouter.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.stratagile.pnrouter.db.DraftEntity;
import com.stratagile.pnrouter.db.EmailAttachEntity;
import com.stratagile.pnrouter.db.EmailCidEntity;
import com.stratagile.pnrouter.db.EmailConfigEntity;
import com.stratagile.pnrouter.db.EmailContactsEntity;
import com.stratagile.pnrouter.db.EmailMessageEntity;
import com.stratagile.pnrouter.db.FileUploadItem;
import com.stratagile.pnrouter.db.FriendEntity;
import com.stratagile.pnrouter.db.GroupEntity;
import com.stratagile.pnrouter.db.GroupVerifyEntity;
import com.stratagile.pnrouter.db.LocalFileItem;
import com.stratagile.pnrouter.db.LocalFileMenu;
import com.stratagile.pnrouter.db.MessageEntity;
import com.stratagile.pnrouter.db.RecentFile;
import com.stratagile.pnrouter.db.RouterEntity;
import com.stratagile.pnrouter.db.RouterUserEntity;
import com.stratagile.pnrouter.db.SMSEntity;
import com.stratagile.pnrouter.db.UserEntity;

import com.stratagile.pnrouter.db.DraftEntityDao;
import com.stratagile.pnrouter.db.EmailAttachEntityDao;
import com.stratagile.pnrouter.db.EmailCidEntityDao;
import com.stratagile.pnrouter.db.EmailConfigEntityDao;
import com.stratagile.pnrouter.db.EmailContactsEntityDao;
import com.stratagile.pnrouter.db.EmailMessageEntityDao;
import com.stratagile.pnrouter.db.FileUploadItemDao;
import com.stratagile.pnrouter.db.FriendEntityDao;
import com.stratagile.pnrouter.db.GroupEntityDao;
import com.stratagile.pnrouter.db.GroupVerifyEntityDao;
import com.stratagile.pnrouter.db.LocalFileItemDao;
import com.stratagile.pnrouter.db.LocalFileMenuDao;
import com.stratagile.pnrouter.db.MessageEntityDao;
import com.stratagile.pnrouter.db.RecentFileDao;
import com.stratagile.pnrouter.db.RouterEntityDao;
import com.stratagile.pnrouter.db.RouterUserEntityDao;
import com.stratagile.pnrouter.db.SMSEntityDao;
import com.stratagile.pnrouter.db.UserEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig draftEntityDaoConfig;
    private final DaoConfig emailAttachEntityDaoConfig;
    private final DaoConfig emailCidEntityDaoConfig;
    private final DaoConfig emailConfigEntityDaoConfig;
    private final DaoConfig emailContactsEntityDaoConfig;
    private final DaoConfig emailMessageEntityDaoConfig;
    private final DaoConfig fileUploadItemDaoConfig;
    private final DaoConfig friendEntityDaoConfig;
    private final DaoConfig groupEntityDaoConfig;
    private final DaoConfig groupVerifyEntityDaoConfig;
    private final DaoConfig localFileItemDaoConfig;
    private final DaoConfig localFileMenuDaoConfig;
    private final DaoConfig messageEntityDaoConfig;
    private final DaoConfig recentFileDaoConfig;
    private final DaoConfig routerEntityDaoConfig;
    private final DaoConfig routerUserEntityDaoConfig;
    private final DaoConfig sMSEntityDaoConfig;
    private final DaoConfig userEntityDaoConfig;

    private final DraftEntityDao draftEntityDao;
    private final EmailAttachEntityDao emailAttachEntityDao;
    private final EmailCidEntityDao emailCidEntityDao;
    private final EmailConfigEntityDao emailConfigEntityDao;
    private final EmailContactsEntityDao emailContactsEntityDao;
    private final EmailMessageEntityDao emailMessageEntityDao;
    private final FileUploadItemDao fileUploadItemDao;
    private final FriendEntityDao friendEntityDao;
    private final GroupEntityDao groupEntityDao;
    private final GroupVerifyEntityDao groupVerifyEntityDao;
    private final LocalFileItemDao localFileItemDao;
    private final LocalFileMenuDao localFileMenuDao;
    private final MessageEntityDao messageEntityDao;
    private final RecentFileDao recentFileDao;
    private final RouterEntityDao routerEntityDao;
    private final RouterUserEntityDao routerUserEntityDao;
    private final SMSEntityDao sMSEntityDao;
    private final UserEntityDao userEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        draftEntityDaoConfig = daoConfigMap.get(DraftEntityDao.class).clone();
        draftEntityDaoConfig.initIdentityScope(type);

        emailAttachEntityDaoConfig = daoConfigMap.get(EmailAttachEntityDao.class).clone();
        emailAttachEntityDaoConfig.initIdentityScope(type);

        emailCidEntityDaoConfig = daoConfigMap.get(EmailCidEntityDao.class).clone();
        emailCidEntityDaoConfig.initIdentityScope(type);

        emailConfigEntityDaoConfig = daoConfigMap.get(EmailConfigEntityDao.class).clone();
        emailConfigEntityDaoConfig.initIdentityScope(type);

        emailContactsEntityDaoConfig = daoConfigMap.get(EmailContactsEntityDao.class).clone();
        emailContactsEntityDaoConfig.initIdentityScope(type);

        emailMessageEntityDaoConfig = daoConfigMap.get(EmailMessageEntityDao.class).clone();
        emailMessageEntityDaoConfig.initIdentityScope(type);

        fileUploadItemDaoConfig = daoConfigMap.get(FileUploadItemDao.class).clone();
        fileUploadItemDaoConfig.initIdentityScope(type);

        friendEntityDaoConfig = daoConfigMap.get(FriendEntityDao.class).clone();
        friendEntityDaoConfig.initIdentityScope(type);

        groupEntityDaoConfig = daoConfigMap.get(GroupEntityDao.class).clone();
        groupEntityDaoConfig.initIdentityScope(type);

        groupVerifyEntityDaoConfig = daoConfigMap.get(GroupVerifyEntityDao.class).clone();
        groupVerifyEntityDaoConfig.initIdentityScope(type);

        localFileItemDaoConfig = daoConfigMap.get(LocalFileItemDao.class).clone();
        localFileItemDaoConfig.initIdentityScope(type);

        localFileMenuDaoConfig = daoConfigMap.get(LocalFileMenuDao.class).clone();
        localFileMenuDaoConfig.initIdentityScope(type);

        messageEntityDaoConfig = daoConfigMap.get(MessageEntityDao.class).clone();
        messageEntityDaoConfig.initIdentityScope(type);

        recentFileDaoConfig = daoConfigMap.get(RecentFileDao.class).clone();
        recentFileDaoConfig.initIdentityScope(type);

        routerEntityDaoConfig = daoConfigMap.get(RouterEntityDao.class).clone();
        routerEntityDaoConfig.initIdentityScope(type);

        routerUserEntityDaoConfig = daoConfigMap.get(RouterUserEntityDao.class).clone();
        routerUserEntityDaoConfig.initIdentityScope(type);

        sMSEntityDaoConfig = daoConfigMap.get(SMSEntityDao.class).clone();
        sMSEntityDaoConfig.initIdentityScope(type);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        draftEntityDao = new DraftEntityDao(draftEntityDaoConfig, this);
        emailAttachEntityDao = new EmailAttachEntityDao(emailAttachEntityDaoConfig, this);
        emailCidEntityDao = new EmailCidEntityDao(emailCidEntityDaoConfig, this);
        emailConfigEntityDao = new EmailConfigEntityDao(emailConfigEntityDaoConfig, this);
        emailContactsEntityDao = new EmailContactsEntityDao(emailContactsEntityDaoConfig, this);
        emailMessageEntityDao = new EmailMessageEntityDao(emailMessageEntityDaoConfig, this);
        fileUploadItemDao = new FileUploadItemDao(fileUploadItemDaoConfig, this);
        friendEntityDao = new FriendEntityDao(friendEntityDaoConfig, this);
        groupEntityDao = new GroupEntityDao(groupEntityDaoConfig, this);
        groupVerifyEntityDao = new GroupVerifyEntityDao(groupVerifyEntityDaoConfig, this);
        localFileItemDao = new LocalFileItemDao(localFileItemDaoConfig, this);
        localFileMenuDao = new LocalFileMenuDao(localFileMenuDaoConfig, this);
        messageEntityDao = new MessageEntityDao(messageEntityDaoConfig, this);
        recentFileDao = new RecentFileDao(recentFileDaoConfig, this);
        routerEntityDao = new RouterEntityDao(routerEntityDaoConfig, this);
        routerUserEntityDao = new RouterUserEntityDao(routerUserEntityDaoConfig, this);
        sMSEntityDao = new SMSEntityDao(sMSEntityDaoConfig, this);
        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);

        registerDao(DraftEntity.class, draftEntityDao);
        registerDao(EmailAttachEntity.class, emailAttachEntityDao);
        registerDao(EmailCidEntity.class, emailCidEntityDao);
        registerDao(EmailConfigEntity.class, emailConfigEntityDao);
        registerDao(EmailContactsEntity.class, emailContactsEntityDao);
        registerDao(EmailMessageEntity.class, emailMessageEntityDao);
        registerDao(FileUploadItem.class, fileUploadItemDao);
        registerDao(FriendEntity.class, friendEntityDao);
        registerDao(GroupEntity.class, groupEntityDao);
        registerDao(GroupVerifyEntity.class, groupVerifyEntityDao);
        registerDao(LocalFileItem.class, localFileItemDao);
        registerDao(LocalFileMenu.class, localFileMenuDao);
        registerDao(MessageEntity.class, messageEntityDao);
        registerDao(RecentFile.class, recentFileDao);
        registerDao(RouterEntity.class, routerEntityDao);
        registerDao(RouterUserEntity.class, routerUserEntityDao);
        registerDao(SMSEntity.class, sMSEntityDao);
        registerDao(UserEntity.class, userEntityDao);
    }
    
    public void clear() {
        draftEntityDaoConfig.clearIdentityScope();
        emailAttachEntityDaoConfig.clearIdentityScope();
        emailCidEntityDaoConfig.clearIdentityScope();
        emailConfigEntityDaoConfig.clearIdentityScope();
        emailContactsEntityDaoConfig.clearIdentityScope();
        emailMessageEntityDaoConfig.clearIdentityScope();
        fileUploadItemDaoConfig.clearIdentityScope();
        friendEntityDaoConfig.clearIdentityScope();
        groupEntityDaoConfig.clearIdentityScope();
        groupVerifyEntityDaoConfig.clearIdentityScope();
        localFileItemDaoConfig.clearIdentityScope();
        localFileMenuDaoConfig.clearIdentityScope();
        messageEntityDaoConfig.clearIdentityScope();
        recentFileDaoConfig.clearIdentityScope();
        routerEntityDaoConfig.clearIdentityScope();
        routerUserEntityDaoConfig.clearIdentityScope();
        sMSEntityDaoConfig.clearIdentityScope();
        userEntityDaoConfig.clearIdentityScope();
    }

    public DraftEntityDao getDraftEntityDao() {
        return draftEntityDao;
    }

    public EmailAttachEntityDao getEmailAttachEntityDao() {
        return emailAttachEntityDao;
    }

    public EmailCidEntityDao getEmailCidEntityDao() {
        return emailCidEntityDao;
    }

    public EmailConfigEntityDao getEmailConfigEntityDao() {
        return emailConfigEntityDao;
    }

    public EmailContactsEntityDao getEmailContactsEntityDao() {
        return emailContactsEntityDao;
    }

    public EmailMessageEntityDao getEmailMessageEntityDao() {
        return emailMessageEntityDao;
    }

    public FileUploadItemDao getFileUploadItemDao() {
        return fileUploadItemDao;
    }

    public FriendEntityDao getFriendEntityDao() {
        return friendEntityDao;
    }

    public GroupEntityDao getGroupEntityDao() {
        return groupEntityDao;
    }

    public GroupVerifyEntityDao getGroupVerifyEntityDao() {
        return groupVerifyEntityDao;
    }

    public LocalFileItemDao getLocalFileItemDao() {
        return localFileItemDao;
    }

    public LocalFileMenuDao getLocalFileMenuDao() {
        return localFileMenuDao;
    }

    public MessageEntityDao getMessageEntityDao() {
        return messageEntityDao;
    }

    public RecentFileDao getRecentFileDao() {
        return recentFileDao;
    }

    public RouterEntityDao getRouterEntityDao() {
        return routerEntityDao;
    }

    public RouterUserEntityDao getRouterUserEntityDao() {
        return routerUserEntityDao;
    }

    public SMSEntityDao getSMSEntityDao() {
        return sMSEntityDao;
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

}
