package com.stratagile.pnrouter.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EMAIL_ATTACH_ENTITY".
*/
public class EmailAttachEntityDao extends AbstractDao<EmailAttachEntity, Long> {

    public static final String TABLENAME = "EMAIL_ATTACH_ENTITY";

    /**
     * Properties of entity EmailAttachEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MsgId = new Property(1, String.class, "msgId", false, "MSG_ID");
        public final static Property Account = new Property(2, String.class, "account", false, "ACCOUNT");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property LocalPath = new Property(4, String.class, "localPath", false, "LOCAL_PATH");
        public final static Property Data = new Property(5, byte[].class, "data", false, "DATA");
    }


    public EmailAttachEntityDao(DaoConfig config) {
        super(config);
    }
    
    public EmailAttachEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EMAIL_ATTACH_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MSG_ID\" TEXT," + // 1: msgId
                "\"ACCOUNT\" TEXT," + // 2: account
                "\"NAME\" TEXT," + // 3: name
                "\"LOCAL_PATH\" TEXT," + // 4: localPath
                "\"DATA\" BLOB);"); // 5: data
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EMAIL_ATTACH_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, EmailAttachEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String msgId = entity.getMsgId();
        if (msgId != null) {
            stmt.bindString(2, msgId);
        }
 
        String account = entity.getAccount();
        if (account != null) {
            stmt.bindString(3, account);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String localPath = entity.getLocalPath();
        if (localPath != null) {
            stmt.bindString(5, localPath);
        }
 
        byte[] data = entity.getData();
        if (data != null) {
            stmt.bindBlob(6, data);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, EmailAttachEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String msgId = entity.getMsgId();
        if (msgId != null) {
            stmt.bindString(2, msgId);
        }
 
        String account = entity.getAccount();
        if (account != null) {
            stmt.bindString(3, account);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String localPath = entity.getLocalPath();
        if (localPath != null) {
            stmt.bindString(5, localPath);
        }
 
        byte[] data = entity.getData();
        if (data != null) {
            stmt.bindBlob(6, data);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public EmailAttachEntity readEntity(Cursor cursor, int offset) {
        EmailAttachEntity entity = new EmailAttachEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // msgId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // account
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // localPath
            cursor.isNull(offset + 5) ? null : cursor.getBlob(offset + 5) // data
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, EmailAttachEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMsgId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAccount(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLocalPath(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setData(cursor.isNull(offset + 5) ? null : cursor.getBlob(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(EmailAttachEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(EmailAttachEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(EmailAttachEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
